M48
; DRILL file {KiCad (7.0.0)} date Wed Jan 10 08:15:53 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-10T08:15:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.762
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X90.85Y-47.4
X93.15Y-47.4
T2
X81.46Y-47.584
X81.46Y-49.616
X86.54Y-48.6
T0
M30
