M48
; DRILL file {KiCad (7.0.0)} date Wed Jan 17 13:13:23 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-17T13:13:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.762
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X85.897Y-47.6
X88.197Y-47.6
T2
X84.92Y-51.184
X84.92Y-53.216
X90.0Y-52.2
T0
M30
